// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {execute} from '../models';
import {context} from '../models';

export function Abort(arg1:string):Promise<void>;

export function Run(arg1:string,arg2:Array<string>):Promise<string>;

export function RunAndOutput(arg1:string,arg2:Array<string>,arg3:boolean):Promise<execute.CommandResult>;

export function SetContext(arg1:context.Context):Promise<void>;
