// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort(arg1) {
  return window['go']['execute']['CommandExecutor']['Abort'](arg1);
}

export function Add(arg1) {
  return window['go']['execute']['CommandExecutor']['Add'](arg1);
}

export function Start(arg1) {
  return window['go']['execute']['CommandExecutor']['Start'](arg1);
}

export function Status(arg1) {
  return window['go']['execute']['CommandExecutor']['Status'](arg1);
}
