// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Abort(arg1) {
  return window['go']['execute']['CommandExecutor']['Abort'](arg1);
}

export function Run(arg1, arg2) {
  return window['go']['execute']['CommandExecutor']['Run'](arg1, arg2);
}

export function RunAndOutput(arg1, arg2, arg3) {
  return window['go']['execute']['CommandExecutor']['RunAndOutput'](arg1, arg2, arg3);
}

export function SetContext(arg1) {
  return window['go']['execute']['CommandExecutor']['SetContext'](arg1);
}
