// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {execute} from '../models';

export function Abort(arg1:string):Promise<void>;

export function Add(arg1:execute.Command):Promise<string>;

export function Start(arg1:string):Promise<void>;

export function Status(arg1:string):Promise<string>;
