// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CpuInfo() {
  return window['go']['sysinfo']['SysInfo']['CpuInfo']();
}

export function DiskInfo() {
  return window['go']['sysinfo']['SysInfo']['DiskInfo']();
}

export function DiskParitionInfo() {
  return window['go']['sysinfo']['SysInfo']['DiskParitionInfo']();
}

export function GpuInfo() {
  return window['go']['sysinfo']['SysInfo']['GpuInfo']();
}

export function MemoryInfo() {
  return window['go']['sysinfo']['SysInfo']['MemoryInfo']();
}

export function MotherboardInfo() {
  return window['go']['sysinfo']['SysInfo']['MotherboardInfo']();
}

export function NicInfo() {
  return window['go']['sysinfo']['SysInfo']['NicInfo']();
}

export function UserAccountInfo() {
  return window['go']['sysinfo']['SysInfo']['UserAccountInfo']();
}
