// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sysinfo} from '../models';

export function CpuInfo():Promise<Array<sysinfo.Win32_Processor>>;

export function DiskInfo():Promise<Array<sysinfo.Win32_DiskDrive>>;

export function DiskParitionInfo():Promise<Array<sysinfo.Win32_DiskPartition>>;

export function GpuInfo():Promise<Array<sysinfo.Win32_VideoController>>;

export function MemoryInfo():Promise<Array<sysinfo.Win32_PhysicalMemory>>;

export function MotherboardInfo():Promise<Array<sysinfo.Win32_BaseBoard>>;

export function NicInfo():Promise<Array<sysinfo.Win32_NetworkAdapter>>;

export function UserAccountInfo():Promise<Array<sysinfo.Win32_UserAccount>>;
