# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'defaults_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DefaultsEditor(object):
    def setupUi(self, DefaultsEditor):
        DefaultsEditor.setObjectName("DefaultsEditor")
        DefaultsEditor.resize(232, 209)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DefaultsEditor.sizePolicy().hasHeightForWidth())
        DefaultsEditor.setSizePolicy(sizePolicy)
        DefaultsEditor.setWhatsThis("")
        DefaultsEditor.setAutoFillBackground(False)
        DefaultsEditor.setStyleSheet("font: 10pt \"Microsoft JhengHei\";\n"
"QLineEdit {\n"
"    border: 1px solid grey;\n"
"     border-radius: 3px;\n"
"}")
        DefaultsEditor.setSizeGripEnabled(False)
        DefaultsEditor.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(DefaultsEditor)
        self.gridLayout.setObjectName("gridLayout")
        self.at_retry_cb = QtWidgets.QCheckBox(DefaultsEditor)
        self.at_retry_cb.setText("")
        self.at_retry_cb.setObjectName("at_retry_cb")
        self.gridLayout.addWidget(self.at_retry_cb, 2, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(DefaultsEditor)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(DefaultsEditor)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.async_install_cb = QtWidgets.QCheckBox(DefaultsEditor)
        self.async_install_cb.setText("")
        self.async_install_cb.setObjectName("async_install_cb")
        self.gridLayout.addWidget(self.async_install_cb, 1, 1, 1, 1)
        self.halt_option_dropdown = QtWidgets.QComboBox(DefaultsEditor)
        self.halt_option_dropdown.setObjectName("halt_option_dropdown")
        self.gridLayout.addWidget(self.halt_option_dropdown, 3, 1, 1, 1)
        self.set_passwd_cb = QtWidgets.QCheckBox(DefaultsEditor)
        self.set_passwd_cb.setText("")
        self.set_passwd_cb.setObjectName("set_passwd_cb")
        self.gridLayout.addWidget(self.set_passwd_cb, 4, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(DefaultsEditor)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(DefaultsEditor)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.action_btns = QtWidgets.QDialogButtonBox(DefaultsEditor)
        self.action_btns.setOrientation(QtCore.Qt.Horizontal)
        self.action_btns.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.action_btns.setObjectName("action_btns")
        self.gridLayout.addWidget(self.action_btns, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(DefaultsEditor)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.at_install_cb = QtWidgets.QCheckBox(DefaultsEditor)
        self.at_install_cb.setText("")
        self.at_install_cb.setObjectName("at_install_cb")
        self.gridLayout.addWidget(self.at_install_cb, 0, 1, 1, 1)
        self.set_passwd_txt = QtWidgets.QLineEdit(DefaultsEditor)
        self.set_passwd_txt.setObjectName("set_passwd_txt")
        self.gridLayout.addWidget(self.set_passwd_txt, 5, 1, 1, 1)

        self.retranslateUi(DefaultsEditor)
        self.action_btns.accepted.connect(DefaultsEditor.accept) # type: ignore
        self.action_btns.rejected.connect(DefaultsEditor.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DefaultsEditor)

    def retranslateUi(self, DefaultsEditor):
        _translate = QtCore.QCoreApplication.translate
        DefaultsEditor.setWindowTitle(_translate("DefaultsEditor", "編輯預設選項"))
        self.label_2.setText(_translate("DefaultsEditor", "同步安裝"))
        self.label_5.setText(_translate("DefaultsEditor", "設定密碼"))
        self.label_3.setText(_translate("DefaultsEditor", "失敗重試"))
        self.label.setText(_translate("DefaultsEditor", "自動安裝"))
        self.label_4.setText(_translate("DefaultsEditor", "關機選項"))
