# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\driver_editor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DriverConfigEditor(object):
    def setupUi(self, DriverConfigEditor):
        DriverConfigEditor.setObjectName("DriverConfigEditor")
        DriverConfigEditor.resize(531, 299)
        DriverConfigEditor.setStyleSheet("font: 10pt \"Microsoft JhengHei\";")
        self.verticalLayoutWidget = QtWidgets.QWidget(DriverConfigEditor)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 101, 111))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.dri_info_scrollarea = QtWidgets.QScrollArea(DriverConfigEditor)
        self.dri_info_scrollarea.setGeometry(QtCore.QRect(120, 10, 401, 281))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.dri_info_scrollarea.setFont(font)
        self.dri_info_scrollarea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.dri_info_scrollarea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dri_info_scrollarea.setWidgetResizable(True)
        self.dri_info_scrollarea.setObjectName("dri_info_scrollarea")
        self.dri_info_sa_contents = QtWidgets.QWidget()
        self.dri_info_sa_contents.setGeometry(QtCore.QRect(0, 0, 382, 279))
        self.dri_info_sa_contents.setObjectName("dri_info_sa_contents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.dri_info_sa_contents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.dri_info_sa_contents)
        self.tableWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tableWidget.setStyleSheet("QHeaderView::section {\n"
"    color: black;\n"
"    background-color:  rgb(255, 255, 255);\n"
"    border-width: 0px 0px 2px 0px;\n"
"    border-style: dotted;\n"
"}")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.SolidLine)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.dri_info_scrollarea.setWidget(self.dri_info_sa_contents)
        self.horizontalLayoutWidget = QtWidgets.QWidget(DriverConfigEditor)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 250, 101, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_4 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout.addWidget(self.pushButton_4)

        self.retranslateUi(DriverConfigEditor)
        QtCore.QMetaObject.connectSlotsByName(DriverConfigEditor)

    def retranslateUi(self, DriverConfigEditor):
        _translate = QtCore.QCoreApplication.translate
        DriverConfigEditor.setWindowTitle(_translate("DriverConfigEditor", "編輯軀動程式"))
        self.pushButton_2.setText(_translate("DriverConfigEditor", "有線網絡介卡"))
        self.pushButton.setText(_translate("DriverConfigEditor", "顯示卡"))
        self.pushButton_3.setText(_translate("DriverConfigEditor", "其他"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DriverConfigEditor", "軀動名稱"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DriverConfigEditor", "路徑"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DriverConfigEditor", "安裝參數"))
        self.pushButton_4.setText(_translate("DriverConfigEditor", "新增"))
