// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {porter} from '../models';

export function Abort():Promise<void>;

export function Export(arg1:string):Promise<void>;

export function ImportFromFile(arg1:string,arg2:boolean):Promise<void>;

export function ImportFromURL(arg1:string,arg2:boolean):Promise<void>;

export function Progress():Promise<porter.Progresses>;

export function Status():Promise<string>;
