# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InstallProgress(object):
    def setupUi(self, InstallProgress):
        InstallProgress.setObjectName("InstallProgress")
        InstallProgress.resize(321, 210)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(InstallProgress.sizePolicy().hasHeightForWidth())
        InstallProgress.setSizePolicy(sizePolicy)
        self.progressTable = QtWidgets.QTableWidget(InstallProgress)
        self.progressTable.setGeometry(QtCore.QRect(10, 10, 301, 192))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.progressTable.setFont(font)
        self.progressTable.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.progressTable.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.progressTable.setFrameShadow(QtWidgets.QFrame.Plain)
        self.progressTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.progressTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.progressTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.progressTable.setTabKeyNavigation(False)
        self.progressTable.setProperty("showDropIndicator", False)
        self.progressTable.setDragDropOverwriteMode(False)
        self.progressTable.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.progressTable.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerItem)
        self.progressTable.setShowGrid(True)
        self.progressTable.setGridStyle(QtCore.Qt.SolidLine)
        self.progressTable.setWordWrap(True)
        self.progressTable.setCornerButtonEnabled(False)
        self.progressTable.setObjectName("progressTable")
        self.progressTable.setColumnCount(2)
        self.progressTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.progressTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.progressTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.progressTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.progressTable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.progressTable.setItem(0, 1, item)
        self.progressTable.horizontalHeader().setVisible(True)
        self.progressTable.horizontalHeader().setCascadingSectionResizes(False)
        self.progressTable.horizontalHeader().setDefaultSectionSize(150)
        self.progressTable.horizontalHeader().setHighlightSections(True)
        self.progressTable.horizontalHeader().setMinimumSectionSize(150)
        self.progressTable.horizontalHeader().setSortIndicatorShown(False)
        self.progressTable.verticalHeader().setVisible(False)
        self.progressTable.verticalHeader().setCascadingSectionResizes(False)
        self.progressTable.verticalHeader().setHighlightSections(False)

        self.retranslateUi(InstallProgress)
        QtCore.QMetaObject.connectSlotsByName(InstallProgress)

    def retranslateUi(self, InstallProgress):
        _translate = QtCore.QCoreApplication.translate
        InstallProgress.setWindowTitle(_translate("InstallProgress", "Form"))
        item = self.progressTable.verticalHeaderItem(0)
        item.setText(_translate("InstallProgress", "1"))
        item = self.progressTable.horizontalHeaderItem(0)
        item.setText(_translate("InstallProgress", "Driver"))
        item = self.progressTable.horizontalHeaderItem(1)
        item.setText(_translate("InstallProgress", "Status"))
        __sortingEnabled = self.progressTable.isSortingEnabled()
        self.progressTable.setSortingEnabled(False)
        item = self.progressTable.item(0, 0)
        item.setText(_translate("InstallProgress", "123"))
        item = self.progressTable.item(0, 1)
        item.setText(_translate("InstallProgress", "1123"))
        self.progressTable.setSortingEnabled(__sortingEnabled)
