// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecutableExists(arg1) {
  return window['go']['main']['App']['ExecutableExists'](arg1);
}

export function PathExists(arg1) {
  return window['go']['main']['App']['PathExists'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SetContext(arg1) {
  return window['go']['main']['App']['SetContext'](arg1);
}
