// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function AppBinaryType():Promise<string>;

export function AppConfigPath():Promise<string>;

export function AppDriverPath():Promise<string>;

export function AppVersion():Promise<string>;

export function Cwd():Promise<string>;

export function ExecutableExists(arg1:string):Promise<boolean>;

export function PathExists(arg1:string):Promise<boolean>;

export function SelectFile(arg1:boolean):Promise<string>;

export function SelectFolder(arg1:boolean):Promise<string>;

export function SetContext(arg1:context.Context):Promise<void>;

export function Update(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WebView2Path():Promise<string>;

export function WebView2Version():Promise<string>;
