// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Add(arg1:store.DriverGroup):Promise<string>;

export function Get(arg1:string):Promise<store.DriverGroup>;

export function GroupOf(arg1:string):Promise<string>;

export function IndexOf(arg1:string):Promise<number>;

export function MoveBehind(arg1:string,arg2:number):Promise<Array<store.DriverGroup>>;

export function Read():Promise<Array<store.DriverGroup>>;

export function Remove(arg1:string):Promise<void>;

export function Update(arg1:store.DriverGroup):Promise<void>;
