// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['store']['DriverManager']['Add'](arg1);
}

export function Get(arg1) {
  return window['go']['store']['DriverManager']['Get'](arg1);
}

export function IndexOf(arg1) {
  return window['go']['store']['DriverManager']['IndexOf'](arg1);
}

export function PathExist(arg1) {
  return window['go']['store']['DriverManager']['PathExist'](arg1);
}

export function Read() {
  return window['go']['store']['DriverManager']['Read']();
}

export function Remove(arg1) {
  return window['go']['store']['DriverManager']['Remove'](arg1);
}

export function Update(arg1) {
  return window['go']['store']['DriverManager']['Update'](arg1);
}
