// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {store} from '../models';

export function Add(arg1:store.Driver):Promise<void>;

export function Get(arg1:string):Promise<store.Driver>;

export function IndexOf(arg1:string):Promise<number>;

export function PathExist(arg1:string):Promise<boolean>;

export function Read():Promise<Array<store.Driver>>;

export function Remove(arg1:store.Driver):Promise<void>;

export function Update(arg1:store.Driver):Promise<void>;
