// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Add(arg1) {
  return window['go']['store']['DriverGroupManager']['Add'](arg1);
}

export function Get(arg1) {
  return window['go']['store']['DriverGroupManager']['Get'](arg1);
}

export function GroupOf(arg1) {
  return window['go']['store']['DriverGroupManager']['GroupOf'](arg1);
}

export function IndexOf(arg1) {
  return window['go']['store']['DriverGroupManager']['IndexOf'](arg1);
}

export function MoveBehind(arg1, arg2) {
  return window['go']['store']['DriverGroupManager']['MoveBehind'](arg1, arg2);
}

export function Read() {
  return window['go']['store']['DriverGroupManager']['Read']();
}

export function Remove(arg1) {
  return window['go']['store']['DriverGroupManager']['Remove'](arg1);
}

export function Update(arg1) {
  return window['go']['store']['DriverGroupManager']['Update'](arg1);
}
